services:
  - type: web
    name: ecommerce-backend
    env: python
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_1vCaQbPAeR9w@ep-weathered-smoke-a4j9f83e-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require"
      - key: SECRET_KEY
        value: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
      - key: ALLOWED_ORIGINS
        value: ""

  - type: static_site
    name: ecommerce-frontend
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: "https://ecommerce-backend.onrender.com"
